### PR TITLE
Add one more error code which is LDAP_PARTIAL_RESULTS: 9

### PR DESCRIPTION
**Pull request by gaupoit**
Related to this issue: https://github.com/mcavage/node-ldapjs/issues/366

### CODE REVIEW

**Comment by frostie614** [comment]
I have been doing a quick search for information related to this and have found the following:

**[Microsoft](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ldap/return-values#LDAP_PARTIAL_RESULTS)**
[LdapWiki](https://ldapwiki.com/wiki/LDAP%20Result%20Codes)
[IBM](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.glpa400/lsrc.htm)

Is this of any use?

**Comment by frostie614** [comment]
I have been doing a quick search for information related to this and have found the following:

**[Microsoft](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/ldap/return-values#LDAP_PARTIAL_RESULTS)**
[LdapWiki](https://ldapwiki.com/wiki/LDAP%20Result%20Codes)
[IBM](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.glpa400/lsrc.htm)

Is this of any use?

**Comment by jsumners** [comment]
@frostie614 yep. That answers it.

A follow-up PR that adds a working integration test would be ideal, but I have no idea how to force it.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.

**Pull request closed without merging**
