### PR TITLE
Client won't work after minification is done. 

### PR DESCRIPTION
**Pull request by grogi**
The client did not work after the uglification/minification was performed.

Replaced the manipulations on the name of the class with an expect results of said manipulations.

### CODE REVIEW

**Comment by frostie614** [comment]
Hi @jsumners  I am new to all this but I was wondering what needs to be done to get this fix merged. I am willing to contribute with some guidance. Thank you

**Comment by jsumners** [comment]
@frostie614 I basically just need to know if this change is covered by any of the unit tests. And, if not, a unit test added for it.

**Comment by frostie614** [comment]
@jsumners I see there are tests in test/client.test.js which have assertions on 'searchEntry' and 'searchReference' and ensure they are okay. Is that all that needs testing? If not, what would you like covered by tests and I will check if there is a test to cover it, or implement one if there is not.

**Comment by jsumners** [comment]
I missed earlier that this is targeting the `master` branch. It should also be refactored to target the `next` branch. Once that is done, you should be able to run `npm run test:cov:html` to get a report that will allow you to determine if both branches are covered by the test suite.

**Comment by frostie614** [comment]
I have merged the change into the next branch.
I have run the coverage report. Both branches are covered.
Is that all? Do I need to raise a new pull request?
Thank you

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.

**Pull request closed without merging**
