### PR TITLE
fix: modifyDn length fix

### LINKED ISSUE #740: client.modifyDN fails
client.modifyDN fails without any error message when dn is more than 112 characters

### PR DESCRIPTION
**Pull request by JohnTJohnston**
This should resolve #740.

### CODE REVIEW

**Comment by UziTech** [comment]
Can you write a test for this?

**Comment by JohnTJohnston** [comment]
This should repro testing against AD. In my case, the new superior was 0x86 bytes long, and wireshark ldap disector flagged the length as illegal.  Refer to "BER Lengths" in [https://ldap.com/ldapv3-wire-protocol-reference-asn1-ber/](url)

```
const cn = "cn=existing user";
const oldDn = cn + ",ou=users,dc=aCompany,dc=com";
const newDn = cn + ",someLongNewSuperiorGreaterThan0x80Lengh";

client.modifyDN(oldDn, newDn, (err) => {
    if (err) console.log(err);
    else console.log("ok");
});
```

Running above will log "ok", but the object is not moved.

**Review by jsumners — CHANGES_REQUESTED** [review]
We need at least an integration test in the same vein as https://github.com/ldapjs/node-ldapjs/blob/91de94d1a625b66b753091697632cbc6f433913d/test-integration/client/issues.test.js#L12-L41

**Review by jsumners — CHANGES_REQUESTED** [review]
We need at least an integration test in the same vein as https://github.com/ldapjs/node-ldapjs/blob/91de94d1a625b66b753091697632cbc6f433913d/test-integration/client/issues.test.js#L12-L41

**Comment by JohnTJohnston** [comment]
That won't work.  The new superior must be long.  A long RDN will not repro the problem.  So the test can only be written if your test directory has an existing long superior, which in my case was an OU.

**Comment by JohnTJohnston** [comment]
Perhaps I'm missing the point of your unit/integration tests.  Is it essential to reproduce a failure prior to the fix?  Is it possible for unit tests to get access to the output BER stream to confirm that the length was inserted  correctly?

**Comment by jsumners** [comment]
> That won't work. The new superior must be long. A long RDN will not repro the problem. So the test can only be written if your test directory has an existing long superior, which in my case was an OU.

I am showing an example of a test for a _similar_ problem. One would need to be written to cover this problem.

> Perhaps I'm missing the point of your unit/integration tests. Is it essential to reproduce a failure prior to the fix? Is it possible for unit tests to get access to the output BER stream to confirm that the length was inserted correctly?

Yes. It is essential. Otherwise we have no proof that the code does what it is purported to do. It also helps prevent changes in the future that would re-introduce the problem.

**Review by UziTech — APPROVED** [review]
LGTM

**Review by jsumners — APPROVED** [review]
Fantastic! Everything checks out locally. Thank you for providing the test.

Looks good to me.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.

**Pull request merged**
