### PR TITLE
Add integration test for PasswordPolicyControl

### PR DESCRIPTION
**Pull request by its-sami**
Testing for [this change](https://github.com/ldapjs/controls/pull/4)

### CODE REVIEW

**Review by jsumners — CHANGES_REQUESTED** [review]
Thank you for working on this. A couple of things to get started:

1. https://github.com/ldapjs/node-ldapjs/blob/bec2ff8e7399155ebdcbf86eec2077a792b8510b/docker-compose.yml#L3 will need to be updated to use the `2023-10-30` image tag.
2. Please put the new test in its own test file, e.g. `issue-946.test.js`, as other recent tests have done. It was a mistake to try and put all tests in a singluar `issues.test.js` suite.

**Comment by its-sami** [comment]
No problem! I've handled both parts and cleaned up a little.

**Review by jsumners — COMMENTED** [review]
Given that the tests now rely on a feature added in a later release, we need to update https://github.com/ldapjs/node-ldapjs/blob/bec2ff8e7399155ebdcbf86eec2077a792b8510b/package.json#L17 to reference v2.1.0.

**Comment by its-sami** [comment]
Right, I've also handled the required bump to messages [here](https://github.com/ldapjs/messages/pull/8)

**Review by jsumners — COMMENTED** [review]
We need to update this line as well and then everything should pass:

https://github.com/ldapjs/node-ldapjs/blob/bec2ff8e7399155ebdcbf86eec2077a792b8510b/.github/workflows/integration.yml#L23

**Comment by its-sami** [comment]
Amazing, thank you

**Review by jsumners — APPROVED** [review]
Looks good. Thank you for the diligent effort.

**Pull request merged**
