### PR TITLE
Remove unused variables

### PR DESCRIPTION
**Pull request by ccouzens**
These were identified by this report
https://lgtm.com/projects/g/ldapjs/node-ldapjs/?mode=list

And then verified by my editor (Visual Studio Code's Typescript compiler
- yes it also works on Javascript), and by me manually searching through
each file.

Removing unused variables helps people concentrate on what's important,
and will highlight more important issues in the lgtm.com report.

### CODE REVIEW

**Comment by jsumners** [comment]
All work is currently proceeding on the `next` branch. Please base your off if it.

**Comment by ccouzens** [comment]
It looks like on the `next` branch all the various unused imports have been removed or at least commented out. As such, there's nothing to do and I'll close this.

**Comment by jsumners** [comment]
;)

I knew that. I commented them out because I'm going to clean them up as I spend more time in code clean up.

**Comment by jsumners** [comment]
⚠️ This issue has been locked due to age. If you have encountered a recent
problem that seems to be covered by this issue, please open a new issue.

Please include a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)
when opening a new issue.

**Pull request closed without merging**
