### PR TITLE
 WIP - Enable modification of thumbnailPhotos

### PR DESCRIPTION
**Pull request by sinistersig**
See #333 for more details

### CODE REVIEW

**Comment by geoffginley** [comment]
+1

Any news on this?

**Comment by jsumners** [comment]
@sinistersig can you explain to me if https://github.com/ldapjs/node-ldapjs/pull/383 would also solve the problem?

**Comment by sinistersig** [comment]
I'm not entirely sure. I can try updating the PR. The reason why it failed is the `isBuffer` function is not available in ancient versions of node. I thought it would've been fixed by now :)

**Comment by jsumners** [comment]
Rebase onto the `next` branch and don’t worry about Node < 10.

**Comment by sinistersig** [comment]
@jsumners, I fixed it for v0.10.x however #508 is preventing all the tests from passing in travis

**Comment by sinistersig** [comment]
Closing to reopen a new PR

**Pull request closed without merging**
